data "oci_objectstorage_namespace" "ns" {
  compartment_id = var.compartment_ocid
}

# ---------------------------------------------------------------------------
# internal-01's SSH key pair, generated by Terraform (not the operator) --
# the private half is planted ONLY as an Object Storage object behind a
# Pre-Authenticated Request URL, which is exactly what an attacker has to
# find via web-01's SSRF-leaked instance metadata. Nobody manually manages
# or copies this key. Object Storage (not a "Vault" secret) specifically
# because it's covered by OCI's Always Free tier (10GB) with zero cost --
# OCI Vault is not part of Always Free.
# ---------------------------------------------------------------------------
resource "tls_private_key" "internal01" {
  algorithm = "RSA"
  rsa_bits  = 3072
}

resource "oci_objectstorage_bucket" "secrets" {
  compartment_id = var.compartment_ocid
  namespace      = data.oci_objectstorage_namespace.ns.namespace
  name           = "cloudbreach-secrets"
  access_type    = "NoPublicAccess"
}

resource "oci_objectstorage_object" "internal01_key" {
  namespace = data.oci_objectstorage_namespace.ns.namespace
  bucket    = oci_objectstorage_bucket.secrets.name
  object    = "internal01-ssh-key.pem"
  content   = tls_private_key.internal01.private_key_pem
}

# A pre-authenticated request: a plain, unauthenticated HTTPS GET URL that
# grants time-limited read access to exactly this one object -- OCI's
# equivalent of an S3 presigned URL. This is what web-01's instance
# metadata carelessly points at (see compute.tf's `metadata` block) --
# stashing a presigned/PAR URL in instance metadata is a real, documented
# real-world misconfiguration pattern, not a lab-only shortcut.
resource "oci_objectstorage_preauthrequest" "internal01_key_par" {
  namespace    = data.oci_objectstorage_namespace.ns.namespace
  bucket       = oci_objectstorage_bucket.secrets.name
  name         = "cloudbreach-internal01-key-par"
  access_type  = "ObjectRead"
  object_name  = oci_objectstorage_object.internal01_key.object
  time_expires = var.par_expiration
}
